package com.example.test.entity;


import java.io.Serializable;
import java.util.Date;

public class FileContent implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.FILE_ID
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private String fileId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.FILE_NAME
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private String fileName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.FILE_SIZE
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private Long fileSize;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.upload_path
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private String uploadPath;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.view_path
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private String viewPath;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.REMARK
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private String remark;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.sigin
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private String sigin;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.FILE_TYPE
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private String fileType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.IMG_WIDTH
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private Long imgWidth;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.IMG_HEIGHT
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private Long imgHeight;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.UPDATE_TIME
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private Date updateTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file_content.UPDATE_USER
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.FILE_ID
     *
     * @return the value of file_content.FILE_ID
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.FILE_ID
     *
     * @param fileId the value for file_content.FILE_ID
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.FILE_NAME
     *
     * @return the value of file_content.FILE_NAME
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.FILE_NAME
     *
     * @param fileName the value for file_content.FILE_NAME
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.FILE_SIZE
     *
     * @return the value of file_content.FILE_SIZE
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.FILE_SIZE
     *
     * @param fileSize the value for file_content.FILE_SIZE
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.upload_path
     *
     * @return the value of file_content.upload_path
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public String getUploadPath() {
        return uploadPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.upload_path
     *
     * @param uploadPath the value for file_content.upload_path
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setUploadPath(String uploadPath) {
        this.uploadPath = uploadPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.view_path
     *
     * @return the value of file_content.view_path
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public String getViewPath() {
        return viewPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.view_path
     *
     * @param viewPath the value for file_content.view_path
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setViewPath(String viewPath) {
        this.viewPath = viewPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.REMARK
     *
     * @return the value of file_content.REMARK
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.REMARK
     *
     * @param remark the value for file_content.REMARK
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.sigin
     *
     * @return the value of file_content.sigin
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public String getSigin() {
        return sigin;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.sigin
     *
     * @param sigin the value for file_content.sigin
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setSigin(String sigin) {
        this.sigin = sigin;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.FILE_TYPE
     *
     * @return the value of file_content.FILE_TYPE
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.FILE_TYPE
     *
     * @param fileType the value for file_content.FILE_TYPE
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.IMG_WIDTH
     *
     * @return the value of file_content.IMG_WIDTH
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public Long getImgWidth() {
        return imgWidth;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.IMG_WIDTH
     *
     * @param imgWidth the value for file_content.IMG_WIDTH
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setImgWidth(Long imgWidth) {
        this.imgWidth = imgWidth;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.IMG_HEIGHT
     *
     * @return the value of file_content.IMG_HEIGHT
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public Long getImgHeight() {
        return imgHeight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.IMG_HEIGHT
     *
     * @param imgHeight the value for file_content.IMG_HEIGHT
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setImgHeight(Long imgHeight) {
        this.imgHeight = imgHeight;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.UPDATE_TIME
     *
     * @return the value of file_content.UPDATE_TIME
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.UPDATE_TIME
     *
     * @param updateTime the value for file_content.UPDATE_TIME
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file_content.UPDATE_USER
     *
     * @return the value of file_content.UPDATE_USER
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file_content.UPDATE_USER
     *
     * @param updateUser the value for file_content.UPDATE_USER
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
}
