spring:
 datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.3.126:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
  username: s_root
  password: 1Q2w3e
 redis:
  host: 127.0.0.1 # Redis服务器地址
  database: 0 # Redis数据库索引（默认为0）
  port: 6379 # Redis服务器连接端口
  password:  # Redis服务器连接密码（默认为空）
  timeout: 3000 # 连接超时时间（毫秒）
  jedis:
   pool:
    max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
    max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 100 # 连接池中的最大空闲连接
    min-idle: 0 # 连接池中的最小空闲连接
 elasticsearch:
  rest:
   uris: http://localhost:9200

logging:
 level:
  root: info

common:
 default:
  password: yongyi1234@
 auth:
  path: /index.jsp
 icons:
  path: /resources/icons
file:
 upload:
  path: E:/workspace/upload/
 view:
  path: /upload/view/
#百度AI
baidu:
 #api
 api:
  baseUrl: https://aip.baidubce.com/
  idCardOcrUrl: https://aip.baidubce.com/rest/2.0/ocr/v1/idcard
  #invoiceOcrUrl：https://aip.baidubce.com/rest/2.0/ocr/v1/vat_invoice
  appId: 17597636
  apiKey: B5zxHTgvNI33tCqn31fwKGb9
  sercetKey: NkjSMn0IvtQQh1FXFt6TefP8UcuR3giR

elasticsearch:
 nodes: 127.0.0.1:9200
 schema: http
 max-connect-total: 50
 max-connect-per-route: 10
 connection-request-timeout-millis: 500
 socket-timeout-millis: 30000
 connect-timeout-millis: 1000
 #索引名称
 indexName: user
 xpack:
  security:
   enabled: false
 cluster:
  name: my-elasticsearch # elasticsearch集群名称
 http:
  ip: 127.0.0.1
  port: 9200 # elasticsearch服务端口号
 transport:
  tcp:
   port: 9300 # 集群间通信端口号

#显式禁用安全选项
cluster:
 name: "docker-cluster"
network:
 host: 0.0.0.0
xpack:
 security:
  enabled: false

nacos:
 config:
  server-addr: 127.0.0.1:8848
 discovery:
  server-addr: 127.0.0.1:8848