server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
  jsp:
    init-parameters:
      development: true

spring:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  elasticsearch:
    rest:
      uris: http://localhost:9200