spring:
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            #ID设置为自动获取 每一个必须不同 （所有调度器实例中是唯一的）
            instanceId: AUTO
            #指定调度程序的主线程是否应该是守护线程
            makeSchedulerThreadDaemon: true
          jobStore:
            #数据保存方式为持久化
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            #StdJDBCDelegate说明支持集群
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            #quartz内部表的前缀
            tablePrefix: QRTZ_
            #是否加入集群
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            #容许的最大作业延长时间
            misfireThreshold: 25000
          threadPool:
            #ThreadPool实现的类名
            class: org.quartz.simpl.SimpleThreadPool
            #线程数量
            threadCount: 10
            #线程优先级
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
            #ThreadPool配置线程守护进程
            makeThreadsDaemons: true
    #数据库方式
    job-store-type: jdbc
      #初始化表结构
      #jdbc:
    #initialize-schema: never