server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: nacos
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  freemarker:
    check-template-location: false
  profiles:
    active: test
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #id生成策略
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      #自定义填充策略接口实现
      meta-object-handler: com.example.test.handler.MyMetaObjectHandler