package com.example.test.service.mapper;

import com.example.test.entity.FileContent;
import com.example.test.entity.FileContentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FileContentMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_content
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    int countByExample(FileContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_content
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    int deleteByExample(FileContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_content
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    int deleteByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_content
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    int insert(FileContent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_content
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    int insertSelective(FileContent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_content
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    List<FileContent> selectByExample(FileContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_content
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    FileContent selectByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_content
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") FileContent record,
                                 @Param("example") FileContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_content
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    int updateByExample(@Param("record") FileContent record,
                        @Param("example") FileContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_content
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    int updateByPrimaryKeySelective(FileContent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table file_content
     *
     * @mbggenerated Tue Apr 23 15:54:14 CST 2019
     */
    int updateByPrimaryKey(FileContent record);
}
